#MicroServiceId
spring.application.name=user-service

#DataSourceConfiguration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##premsai
spring.datasource.password=prem123
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#ServerConfiguraion
server.port=8001
server.servlet.context-path=/user

#JpaConfiguraion
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#DevTools
spring.devtools.restart.enabled=true


