#MicroServiceId
spring.application.name=user-service

#ServerConfiguraion
server.port=8001
server.servlet.context-path=/user

#JpaConfiguraion
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#DevTools
spring.devtools.restart.enabled=true

#EurekaServiceUrl
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#ConfigServerUrl
spring.config.import=optional:configserver:http://localhost:9988/config

#Instead of hostname look for ipAddr
eureka.instance.ip-address=true